Update editor.blade.php
laravel-admin-extensions/UEditor pull request #39
Opened 2021-09-10 04:23 UTC by imnpc

支持编辑器额外参数

2021-12-28 07:13 UTC, jxlwqq requested changes

2021-12-28 07:13 UTC, jxlwqq commented on README.md
> +composer require imnpc/ueditor
这里需要恢复下。

2021-12-28 07:13 UTC, jxlwqq commented on composer.json
> +    "name": "imnpc/ueditor",
这里需要恢复下。

2022-03-14 06:42 UTC, imnpc commented on composer.json
> +    "name": "imnpc/ueditor",
已修改

2022-03-17 03:17 UTC, closed without merging